### ISSUE TITLE
How to convert `SRAW_VOC` and `SRAW_NOx` to `µg/m3` or `ppb`

### ISSUE THREAD

**Issue by BelKed** [Sensirion/arduino-i2c-sgp41#1]
Hi there!

I would like to know how to convert measured `SRAW_VOC` and `SRAW_NOx` to suitable units, such as `µg/m3` or `ppb`. After searching on the web for a while, I couldn't find an answer.

Thanks in advance,
BelKed

**Comment by psachs** [comment]
Hi @BelKed 

Sensirion does not support absolute outputs for its VOC and NOx feature derived from SGP signals. For more details, please, refer to https://sensirion.com/media/documents/D27F03C0/6294E00F/Info_Note_Output_MOX_Sensor.pdf
