### ISSUE TITLE
conditioning time in exampleUsage.ino

### ISSUE THREAD

**Issue by Spasstinity** [Sensirion/arduino-i2c-sgp41#5]
In the example, time of conditioning is based on the delay in void loop().
According to the datasheet, a 10 second conditioning time (=heating of the sensor) 
is recommendet before the first measurement is taken, but that 10 seconds must not be exceeded as the sensor may be subjected to overheating and damage.

It may be better to use a timer and refer to the problem or even use a delay and take a measurement during setup to prevent damaging the senor if a user manipulates the code without minding this (shame on me).

**Comment by sdmueller** [comment]
Hi @Spasstinity 

Thanks for using our sensors and pointing out this out!
This is indeed very unfortunate.

I will bring up the issue in the team and we'll see how we want to make that more clear in the example usage.
