### ISSUE TITLE
Unable to read sensor, despite i2c address found

### ISSUE THREAD

**Issue by MartimFernandes** [Sensirion/arduino-i2c-sgp41#8]
I'm trying to read an SGP41 module from an ESP32 dev board (ESP32-WROOM-32D).

![image](https://github.com/Sensirion/arduino-i2c-sgp41/assets/88904228/b417b5c1-261c-4ae9-bbca-60e26b8243a9)

The example code doesn't work (I get the NACK error), so I tried to scan the i2c addresses and it is found with the correct value (0x59).

I then tried manually passing bytes to get the serial number and self-diagnostic, both fail. I don't have an oscilloscope to debug the SCA/SCA pins, but I tried lowering the i2c clock and added pullup resistors without any change. The module supposedly works with 3.3 - 5 V, so I also tried changing the 3.3 V to 5 V supply.

Since I had a second module around, I tried to replace it and got the same results. The pins are correct (I also tried inverting them just in case).

I'm wondering if there's something specific to the ESP32 that gets in the way of proper i2c communications with this module.

**Comment by LeonieFierz** [comment]
Hi @MartimFernandes 
Thanks for contacting us. 
The example should work with an ESP32. Do you connect to default I2C pins 21 (SDA) and 22 (SCL) on the ESP? 
Best, Léonie

**Comment by MartimFernandes** [comment]
Hi, yes I used the correct pins. I also tried declaring the pins explicitly to avoid any potential problems (did the same with the 0x59 address).
I should add I found an old Arduino UNO board and the exact same code ran flawlessly in it, with both sensors. So I'm thinking maybe there's a problem in the i2c communication specific to the ESP32 (but like I said, I don't have an oscilloscope to be sure).

**Comment by LeonieFierz** [comment]
As you see the sensor address, but communication is not working the most likely reason is an bad I2C signal. Without being able to measure it is hard to pin down the reason. The ESP Board has built-in Pull-Ups, so you could try again without adding additional Pull-Ups. Actually I can not say anything about the dev board, as it is not from one of our official partners. Please also make sure that cables are not too long.

**Comment by MartimFernandes** [comment]
I only added the pull-ups afterwards, so it doesn't work either way. Cables are less then 10 cm long, it's all in the same protoboard. Here's a sample image of the dev board I'm using:

![image](https://github.com/Sensirion/arduino-i2c-sgp41/assets/88904228/c3c73ac5-2455-4f12-aa20-ca125e0e900d)

Curiously, the very same board can read a BME280 sensor (also i2c). So I have no idea what the problem is. I think I'm just going to give up and use the UNO for now. Thanks for the responses anyway.
